redis_url = "redis://localhost:6379/0"
extra_modules = ["examples.api_node_examples.api_client"]

[[nodes]]
node_name = "api_client"
node_class = "api_client"

[nodes.node_args]
input_tick_channel = "tick/secs/1"
input_response_channel = "rest_response"
output_channel = "rest_request"


[[nodes]]
node_name = "api_node"
node_class = "rest_api"

[nodes.node_args]
input_channel = "rest_request"
output_channel = "rest_response"
input_type_str = "any"
output_type_str = "any"


[[nodes]]
node_name = "tick"
node_class = "tick"
