name: website
on:
  push:
    branches:
      - main
      - docs/*
env:
  COLUMNS: 150

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - name: checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: true

      - name: install
        run: pip install uv

      - name: checkout current branch
        uses: actions/checkout@v4

      - name: Set git credentials
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - run: uv run mike deploy -b gh-pages latest --push
        if: "github.ref == 'refs/heads/main'"

      - if: "startsWith(github.ref, 'refs/heads/docs')"
        id: check-version
        uses: samuelcolvin/check-python-version@v4.1
        with:
          version_file_path: 'src/aact/__about__.py'
          skip_env_check: true

      - run: uv run mike deploy -b gh-pages ${{ steps.check-version.outputs.VERSION_MAJOR_MINOR }} latest --update-aliases --push
        if: "startsWith(github.ref, 'refs/heads/docs') && !fromJSON(steps.check-version.outputs.IS_PRERELEASE)"
        env:
          PYDANTIC_VERSION: v${{ steps.check-version.outputs.VERSION }}
